### ISSUE TITLE
HTYI: If the game generates a hashtag for a player, they receive points if other players vote for it

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#143]
If a player runs out of time and fails to submit a hashtag, the random hashtag that the game creates for them can still win points if it is voted on.

**Comment by johnnycrich** [comment]
@jpailthorpe Is this a bad thing?

**Comment by jpailthorpe** [comment]
I see an issue where multiple hashtags that get submitted automatically get voted on, but the player associated with that generated hashtag doesn't know which one is there since there is no indication.

I think in an ideal world, the hashtag that autogenerates shouldn't give the player associated points, and instead after the reveal of "who's it is" it shows it as the computer's hashtag. I will add this as a feature in icebox

**Comment by jpailthorpe** [comment]
I'm closing for now. Addressing this will be more so part of a feature that I posted in trello referring to random generated content in general. part of a 1.1 :)
