### ISSUE TITLE
Global: iPhone 4 disconnects from lobby if screen is allowed to power off on its own

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#151]
The device disconnects from the session on the hub screen as soon as the auto-dimmer elapses and the screen powers off completely. This does not happen if the screen is powered on or off manually.

**Comment by jpailthorpe** [comment]
please verify whether this is strictly an iphone4 thing or a an iphone thing in general. Also please note the browser used

**Comment by johnnycrich** [comment]
I am unable to control that iOS disconnect if the device is allowed to sleep. And when a device fully disconnects, I have to clear its local session entirely since otherwise the player will run into issues such as #144. As of a recent fix, I can tell the player they've been disconnected, however they will no longer be in the game.
