### ISSUE TITLE
HTYI:Players being reassigned icons after lobby

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#221]
In HTYI, when starting a game with less than 8 players, all players except Player1 end up losing the icon that they receive at the lobby. The replacement icons appear to be drawn from any that are unused during play, one space removed from the group of actual players. So, for example, if Player1, Player2, Player3, and Player4 start a game from the lobby, Player1 will have Icon1, but Player2 will have Icon6, Player3 will have Icon7, and Player4 will have Icon8.

**Comment by esalling23** [comment]
After some testing, found that this is being caused by the @index number used for linking different icon#'s. In the lobby, the icons are displayed with this @index, but later in the game the players are tied to icons via their playerUID's. If the same "player grid" template is used outside of the lobby, it simply replicates the icon ordering from the lobby screen, regardless of which icons were "assigned" to players when they logged in.

**Comment by jpailthorpe** [comment]
Erica was able to fix this and is now working on making sure her fix works across all the games. expect this in the QA build by EOD tomorrow, but not ready for production before Thursday morning.
