### ISSUE TITLE
WWDMM: Meme Topics can't load image from Keystone

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#223]
![screen shot 2016-11-09 at 5 24 00 pm](https://cloud.githubusercontent.com/assets/12397944/20157144/846e6478-a6a1-11e6-9608-5242c7fcc939.png)

When topics are revealed, the image is replaced by a dead link. Trying to access and follow the attribute back to the resource in the inspector returns a not found error. This occurs even after double-checking the image file in keystone and reuploading it.

**Comment by mattwbenson** [comment]
Think this might be related to images not being square dimensions--the only topic images that load are square ones.

**Comment by esalling23** [comment]
This is likely a content issue, as the images missing were not found on our cloudinary server. Any missing images should be re-uploaded, and tested after the QA or Production server has been rebooted to make sure the changes were updated.

**Comment by jpailthorpe** [comment]
for clarity purposes, I had Sarah resize and upload topic images for WWDMM on production since they were sometimes incorrectly sized or being stretched. I assume this is probably what was going on. I am moving this to done, but lets keep an eye out in our testing tomorrow to see if this is a deeper issue.
