### ISSUE TITLE
Players can submit hashtags with space characters

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#9]
The game should reject any submissions with spaces in them

**Comment by jpailthorpe** [comment]
Or maybe just let it go. It's okay if players don't understand how hashtags are supposed to look (no spaces) since no one will vote on them (unless voters also don't understand). Part of the learning comes In when players realize HOW to fool others players, which demonstrates baseline k owl eve of what a hashtag is, how it's formatted, how it's effective, etc. This somewhat falls under a freedom to fail moment.

**Comment by jpailthorpe** [comment]
*knowledge

**Comment by johnnycrich** [comment]
Seems like we don't need to fix this?

**Comment by jpailthorpe** [comment]
yep leave it for now!
